### ISSUE TITLE
Code needs to be upgraded...

### ISSUE THREAD

**Issue by cheriejw** [MiincGu/react-native-image-button#2]
For example, instead of:                                             
    import React, { Component, View } from 'react-native';   
          
You should now do:    
    import React, { Component } from 'react';              
    import { View } from 'react-native';

Check the release notes on how to upgrade your code - https://github.com/facebook/react-native/releases/tag/v0.25.1

**Comment by thethreeonee** [comment]
Close on PR accepted.
